# We still can't build windows, so we build a dummy package with version 0
{% set version = "2019.2" %}

package:
  name: hugin
  version: {{ version }}  # [not win]
  version: 0.0  # [win]

source:
  #url: https://pilotfiber.dl.sourceforge.net/project/hugin/hugin/hugin-{{ version }}/hugin-{{ version }}.0.tar.bz2
  url: https://iweb.dl.sourceforge.net/project/hugin/hugin/hugin-2019.2/hugin-2019.2.0.tar.bz2
  sha256: 8ba6bdfea246313f142f17f42e066c6888f51b72e4f8814b5e1c84ff56a95a3e

build:
  skip: true  # [osx]
  number: 5


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - cmake
    - swig
    - binutils
    - pkg-config
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
    # Just taken from wxWidgets
    - {{ cdt('libice-devel') }}  # [linux]
    - {{ cdt('libsm-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}  # [linux]
    - {{ cdt('libxcomposite-devel') }}  # [linux]
    - {{ cdt('libxcursor-devel') }}  # [linux]
    - {{ cdt('libxdamage-devel') }}  # [linux]
    - {{ cdt('libxext-devel') }}  # [linux]
    - {{ cdt('libxi-devel') }}  # [linux]
    - {{ cdt('libxinerama-devel') }}  # [linux]
    - {{ cdt('libxfixes-devel') }}  # [linux]
    - {{ cdt('libxrandr-devel') }}  # [linux]
    - {{ cdt('libxrender-devel') }}  # [linux]
    - {{ cdt('libxtst-devel') }}  # [linux]
    - {{ cdt('mesa-libEGL-devel') }}  # [linux]
    - {{ cdt('mesa-libGL-devel') }}  # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
  host:
    - xorg-libxfixes           # [linux]
    - xorg-libsm               # [linux]
    - python
    - pip
    - libtiff
    - libpano13
    - jpeg
    - libpng
    - openexr
    - vigra
    - exiv2
    - glew
    - sqlite
    - lcms2
    - wxwidgets 3.1
    - perl
  run:
    # not sure why run exports isn't working
    - exiftool  # [linux]
    - enblend   # [linux]
    - exiv2     # [linux]
    - xorg-libx11  # [linux]
    - xorg-libsm   # [linux]

test:
  commands:
    - nona -help  # [linux]

about:
  home: http://hugin.sourceforge.net/
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING.txt
  summary: Panorama photo stitcher

  description: |
     Our goal an easy to use cross-platform panoramic imaging toolchain based on Panorama Tools.

    With Hugin you can assemble a mosaic of photographs into a complete
    immersive panorama, stitch any series of overlapping pictures and much
    more.

  doc_url: http://hugin.sourceforge.net/docs/
  dev_url: https://sourceforge.net/projects/hugin/

extra:
  recipe-maintainers:
    - hmaarrfk
